//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoixReponse
    {
        public int id { get; set; }
        public Nullable<int> idSondage { get; set; }
    
        public virtual Sondage Sondage { get; set; }
    }
}
