//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sondage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sondage()
        {
            this.ChoixReponse = new HashSet<ChoixReponse>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> idFormulaire { get; set; }
        public Nullable<int> idSonde { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoixReponse> ChoixReponse { get; set; }
        public virtual Formulaire Formulaire { get; set; }
        public virtual Sonde Sonde { get; set; }
    }
}
