//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composant
    {
        public int IdFormulaire { get; set; }
        public int IdQuestion { get; set; }
        public int IdTypeReponse { get; set; }
    
        public virtual Formulaire Formulaire { get; set; }
        public virtual Question Question { get; set; }
        public virtual TypeReponse TypeReponse { get; set; }
    }
}
